//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookManagementEntities1 : DbContext
    {
        public BookManagementEntities1()
            : base("name=BookManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_bookType> Tbl_bookType { get; set; }
        public virtual DbSet<Tbl_author> Tbl_author { get; set; }
        public virtual DbSet<Tbl_book> Tbl_book { get; set; }
        public virtual DbSet<Tbl_publisher> Tbl_publisher { get; set; }
    }
}
