//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public int booktype_id { get; set; }
        public int author_id { get; set; }
        public int pub_id { get; set; }
        public System.DateTime book_pub_date { get; set; }
        public int ISBN_No { get; set; }
        public int Price { get; set; }
    
        public virtual Tbl_author Tbl_author { get; set; }
        public virtual Tbl_bookType Tbl_bookType { get; set; }
        public virtual Tbl_publisher Tbl_publisher { get; set; }
    }
}
